config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: :show

  resources :blogs
  resources :work_inquiries, only: [:index, :edit, :update, :show]

  resources :admin_users, only: [:index, :edit, :update]

  devise_for :admins, controllers: { sessions: 'sessions', passwords: 'passwords' } #, registrations: 'registrations'}
  

  resource :hire_us, only: [:show, :create] do
    get 'confirmation', on: :member
  end

  root "high_voltage/pages#show", id: 'home'
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :set_post, only: [:edit, :show, :update]
  def index
    @posts = Post.page(params[:page]).per(25)
  end

  def show
  end

  def new
    @post = Post.new
  end


  def create
    begin
      @post = Post.create!(blog_params)
      @post.admins << current_admin
      flash[:success] = "Post Successfully added."
      redirect_to blog_path(@post)
    rescue Exception => e
      @post = Post.new(blog_params)
      flash.now[:error] = "There was an error creating your post."
      render 'new'
    end
  end

  def edit
  end

  def update
    begin
      @post.update_attributes!(blog_params)
      flash[:success] = "Post Successfully updated."
      redirect_to blog_path(@post)      
    rescue Exception => e
      @post = Post.new(blog_params)
      flash.now[:error] = "There was an error updating your post."
      render 'edit'
    end
  end

private 
  def blog_params
    params.require(:post).permit(:title, :tags_text, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/blogs/_blog_header.html.slim
header
  .blog-header
    h2 Thoughts on stuff

app/views/blogs/edit.html.slim
- content_for(:page_title, "Edit: #{@post.title}")
br
div.row
  div.small-12.columns
    = simple_form_for(@post, url: blog_path(@post), html: {method: :put}) do |f|
      = field_set_tag "Edit your thoughts!"
        = f.error_notification 
        = f.input :title
        = f.input :tags_text
        = f.input :body

        = f.submit "Update Blog", class: "button small radius"

app/views/blogs/index.html.slim
- content_for(:page_title, 'stuff to think on')



= render 'blog_header'


section.row.blog-content
  div.small-12.columns
    - for post in @posts do
      article.row
        aside.medium-3.small-12.columns
          h6.text-center.date-aside = post.created_at.strftime("%b %d, %Y")
        div.medium-9.small-12.columns
          h5.text-left.blog-title = link_to post.title, blog_path(post)
      div.row
        div.small-12.medium-9.medium-offset-3.columns
          span.text-justify = render_markdown post.abstract_body
      br
      br
    div.row
      div.panel.large-6.medium-8.small-12.small-centered.columns
        = paginate @posts

app/views/blogs/new.html.slim
- content_for(:page_title, "New Blog Post")
br
div.row
  div.small-12.columns
    = simple_form_for(@post, url: blogs_path) do |f|
      = field_set_tag "Think aloud!"
        = f.error_notification 
        = f.input :title
        = f.input :tags_text
        = f.input :body

        = f.submit "Post To Blog", class: "button small radius"

app/views/blogs/show.html.slim
- content_for(:page_title, @post.title)


= render "blog_header"

div.row
  div.medium-8.medium-offset-2.columns
    h2 = @post.title
hr

div.row
  div.medium-2.small-12.columns
    p = "by #{@post.author}"
    br
    p.date-aside = date_to_appstring(@post.created_at)
    br
    - for tag in @post.tags do
      br = "- #{link_to tag.title, tag_path(tag)}".html_safe

  div.medium-9.end.small-12.columns
    span.text-justify = render_markdown @post.body

- if current_admin and (current_admin.site_admin? or @post.has_owner?(current_admin))
  div.row
    div.medium-4.columns = link_to('edit post', edit_blog_path(@post))