config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: :show

  resources :blogs
  resources :work_inquiries, only: [:index, :edit, :update, :show]

  resources :admin_users, only: [:index, :edit, :update]

  devise_for :admins, controllers: { sessions: 'sessions', passwords: 'passwords' } #, registrations: 'registrations'}
  

  resource :hire_us, only: [:show, :create] do
    get 'confirmation', on: :member
  end

  root "high_voltage/pages#show", id: 'home'
end

app/models/work_inquiry.rb
# Attributes:
# * id [integer, primary, not null] - primary key
# * budget [string] - TODO: document me
# * client_email [string] - maybe one day I will be part of a client model
# * client_name [string] - maybe one day I will be part of a client model
# * client_phone [string] - maybe one day I will be part of a client model
# * created_at [datetime] - creation time
# * job_description [text] - work to be done
# * reference_source [string] - who told you about us?
# * reply [boolean] - has a reply been sent?
# * updated_at [datetime] - last update time
class WorkInquiry < ActiveRecord::Base
  [:budget, :client_name, :client_phone, :job_description, :goals].each do |a|
    validates_presence_of a
  end

  validates :client_email, presence: true,
                           email: { strict_mode: true }

  scope :answered, -> { where(reply: true) }
  scope :unanswered, -> { where(reply: false) }

end

app/controllers/work_inquiries_controller.rb
class WorkInquiriesController < ApplicationController
before_action :verify_approved_admin!
before_action :set_inquiry!, only: [:show, :update, :edit]
  def index
    case 
    when params[:scope_to]== "answered"
      @inquiries_array = WorkInquiry.answered
      @filter = "answered"
    when params[:scope_to] == "unanswered"
      @inquiries_array = WorkInquiry.unanswered
      @filter = "unanswered"
    else
      @inquiries_array = WorkInquiry.all
    end
      @inquiries = Kaminari.paginate_array(@inquiries_array).page(params[:page]).per(10)
  end

  def edit

  end

  def update
   begin
      @inquiry.update_attributes!(work_inquiry_status_params)
      flash[:success] = "Successfully updated status of work inquiry."
      redirect_to work_inquiry_path(@inquiry)
    rescue Exception => e
      render 'edit'
    end
  end

  def show
  end

private 
  def set_inquiry!
    @inquiry = WorkInquiry.find(params[:id])
  end

  def work_inquiry_status_params
    params.require(:work_inquiry).permit(:reply)
  end
end

app/views/work_inquiries/edit.html.slim
- content_for(:page_title, "Edit Work Inquiry")
div.row
  div.12-small.columns
    br
    dl.sub-nav
      dt Action:
      = content_tag(:dd) 
        = link_to "show", work_inquiry_path(@inquiry)
      = content_tag(:dd, class: 'active' )
        = link_to "edit", edit_work_inquiry_path(@inquiry)

hr
div.row
  div.12-small.columns
    p
      strong Client Name:&nbsp;
      = @inquiry.client_name
    p
      strong Client Email:&nbsp;
      = @inquiry.client_email
    p
      strong Client Phone:&nbsp;
      = @inquiry.client_phone
    p
      strong Budget:&nbsp;
      = @inquiry.budget
    p
      strong Job Description:&nbsp;
      = @inquiry.job_description
    p
      strong Referer:&nbsp;
      = @inquiry.reference_source.nil? ? 'NONE' : @inquiry.reference_source
    p
      = simple_form_for(@inquiry, html: { method: :put } ) do |f|
        = field_set_tag "Change Inquiry Status"
          = f.input :reply, label: "Mark Inquiry Replied"

          = f.button :submit, "Update", class: "button small radius"

app/views/work_inquiries/index.html.slim
- content_for(:page_title, "Work Inquiries")

div.row
  div.12-small.columns
    br
    dl.sub-nav
      dt Filter:
      = content_tag(:dd, class: "#{@filter.nil? ? 'active' : ''}") 
        = link_to "All", work_inquiries_path
      = content_tag(:dd, class: "#{@filter == "unanswered" ? 'active' : ''}")
        = link_to "Unanswered", work_inquiries_path( scope_to: 'unanswered')
      = content_tag(:dd, class: "#{@filter == "answered" ? 'active' : ''}")
        = link_to "Answered", work_inquiries_path( scope_to: 'answered')
    hr
    - if @inquiries_array.count > 10
      = paginate @inquiries
      hr
    - for inquiry in @inquiries do
      div.row
        div.10-small.columns
          p
            strong Client Name:&nbsp;
            = inquiry.client_name
      div.row
        div.10-small.columns
          p
            strong Project Budget:&nbsp;
            = inquiry.budget
      div.row
        div.12-small.columns
          p
            strong Project Description:&nbsp;
            = inquiry.job_description

      div.row
        div.5-small.columns = link_to 'show details', work_inquiry_path(inquiry) , id: "show-inquiry-#{inquiry.id}"
        div.5-small.end.columns = link_to 'edit status', edit_work_inquiry_path(inquiry), id: "edit-inquiry-#{inquiry.id}"
      hr

app/views/work_inquiries/show.html.slim
- content_for(:page_title, "Work Inquiry")
div.row
  div.12-small.columns
    br
    dl.sub-nav
      dt Action:
      = content_tag(:dd, class: 'active' ) 
        = link_to "show", work_inquiry_path(@inquiry)
      = content_tag(:dd)
        = link_to "edit", edit_work_inquiry_path(@inquiry)
hr
div.row
  div.12-small.columns
    p
      strong Client Name:&nbsp;
      = @inquiry.client_name
    p
      strong Client Email:&nbsp;
      = @inquiry.client_email
    p
      strong Client Phone:&nbsp;
      = @inquiry.client_phone
    p
      strong Budget:&nbsp;
      = @inquiry.budget
    p
      strong Job Description:&nbsp;
      = @inquiry.job_description
    p
      strong Referer:&nbsp;
      = @inquiry.reference_source.nil? ? 'NONE' : @inquiry.reference_source
    p
      strong Status:&nbsp;
      = @inquiry.reply? ? 'This inquiry has been responded too.': 'Not yet replied.'