config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: :show

  resources :blogs
  resources :work_inquiries, only: [:index, :edit, :update, :show]

  resources :admin_users, only: [:index, :edit, :update]

  devise_for :admins, controllers: { sessions: 'sessions', passwords: 'passwords' } #, registrations: 'registrations'}
  

  resource :hire_us, only: [:show, :create] do
    get 'confirmation', on: :member
  end

  root "high_voltage/pages#show", id: 'home'
end

app/views/layouts/_seo_tags.html.slim
- set_meta_tags description:  "ATEORAMS is a tiny Rails and iOS development consultancy, that can provide development solutions."
- set_meta_tags rights: "ATEORAMS Copyright (C) 2014"
- set_meta_tags keywords: %w(Jacksonville Software ruby rails web apps websites ios osx cocoa)
- set_meta_tags transactional_email: "SendGrid"

= display_meta_tags
title = page_title app_name: "ATEORAMS", separator: "| ", page_title_symbol: :page_title

app/views/layouts/_top_bar.html.slim
header.sticky
  nav[ class="top-bar" data-options="is_hover: false" data-topbar]
    ul.title-area
      li.name
        h1 = link_to root_path do
          = image_tag "Attheedgeof-White.png", alt: "ATEORAMS Home", class: 'top-bar-img'
      li.toggle-topbar.menu-icon = link_to '#' do
        span Menu


    section.top-bar-section
      ul.right
        li.divider
        - if admin_signed_in?
          li.has-dropdown
            = link_to('blog', '#')
            ul.dropdown#blog-dd
              li = link_to 'posts', blogs_path
              li = link_to 'new post', new_blog_path
        - else
          li = link_to 'about', page_path(id: 'about')
        li.divider
          li = link_to 'blog', blogs_path
        li.divider
          li = link_to 'github'
        li.divider
        li = link_to 'hire us', hire_us_path
        - if admin_signed_in?         
          li.divider
          li.has-dropdown 
            = link_to( 'account', '#' )
            ul.dropdown
              li = link_to 'edit', edit_admin_registration_path
              - if current_admin.site_admin?
                li.divider
                li = link_to 'users', admin_users_path
          li.divider
          li = link_to 'sign out',    destroy_admin_session_path, method: :delete

      - if admin_signed_in?
        ul.left
          li.divider
          li = link_to 'work inquiries', work_inquiries_path
          li.divider

app/views/layouts/_zurb.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
   
    = render 'layouts/seo_tags'
    = render 'layouts/zurb'
    - for size in [114, 120, 152, 144, 57, 72, 76] do
      = favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: "apple-touch-icon", sizes: size, type: "image/png" 
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag "vendor/modernizr"

    = stylesheet_link_tag :application, media: 'all'
    = yield :custom_style
    = csrf_meta_tags
  body class=body_class
    = render 'layouts/top_bar'
    = render 'flashes'
    = yield
    = render 'javascript'